version: "3.2"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=logs_db
    volumes:
      - m01:/data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"
volumes:
  m01:
    driver: local
